### ISSUE TITLE
Milestone: Define: Direct Support For Secure Releases And CVE Management

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/security-collab-space#21]
```[tasklist]
### Tasks
- [x] Publish document in the Sec Collab Space Repo with tailored recommendations and best practices, get consensus approval. (https://github.com/openjs-foundation/security-collab-space/pull/70)
- [ ] Create roadmap for bringing OpenJS projects into Compliance, add to dashboard
```

# Create Recommended Best Practices For Secure Releases and CVE Management
1. Research and audit existing best practice guides, such as foo1, foo2
1. Gather feedback from multiple OpenJS projects and stakeholders
1. Based on research, create a document in the Sec Collab Space Repo with tailored recommendations and best practices
1. Get consensus approval on the above page from the Sec Collab Space

# Bring OpenJS projects into Compliance
For each project,
1. Produce a report document evaluating a project against the recommended best practices
1. Approach maintainer(s) and assess willingness to take actions to improve
1. One of:
   - take recommended actions, and produce an updated report document
   - produce a recommendation document outlining suggested actions, and the risks of not completing them
   - {- placeholder for compliance write up - }

**Comment by ljharb** [comment]
1. audit existing best practices guides
    - if needed, create a JS-focused page that heavily leverages/links to existing guides
1. define best practices for "secure releases" and CVE management
    - this step will need to gather lots of feedback and agreement from multiple OpenJS projects and ecosystem experts/stakeholders
1. audit OpenJS projects on the list of critical projects for matching that criteria, once agreed upon
1. for each project on the list of critical OpenJS projects, starting with nvm:
    - audit for that agreed-upon criteria
    - approach maintainer(s) and assess willingness to take actions to improve
    - assist maintainer(s) with those steps
    
The above has a lot of handwaving over "define best practices", but hopefully that step will inform and/or increase confidence in the remaining steps.

**Comment by bensternthal** [comment]
@ljharb for me it would be helpful to understand the artifacts that will be created for each area you are investigating and to have a clear definition of done. Here is an example of that level of detail for step 1 and 2 (I combined these since I think 1 is just a research task). 

**Create Recommended Best Practices For Secure Releases and CVE Management** 
1. Research and audit existing best practice guides, such as foo1, foo2
2. Gather feedback from multiple OpenJS projects and stakeholders 
3. Based on research, create a document in the Sec Collab Space Repo with tailored recommendations and best practices
4. Get consensus approval on the above page from the Sec Collab Space

**Comment by ljharb** [comment]
Makes sense. Updated here:
# Create Recommended Best Practices For Secure Releases and CVE Management
1. Research and audit existing best practice guides, such as foo1, foo2
1. Gather feedback from multiple OpenJS projects and stakeholders
1. Based on research, create a document in the Sec Collab Space Repo with tailored recommendations and best practices
1. Get consensus approval on the above page from the Sec Collab Space

# Bring OpenJS projects into Compliance
For each project,
1. Produce a report document evaluating a project against the recommended best practices
1. Approach maintainer(s) and assess willingness to take actions to improve
1. One of:
   - take recommended actions, and produce an updated report document
   - produce a recommendation document outlining suggested actions, and the risks of not completing them

**Comment by bensternthal** [comment]
@ljharb i think this looks great, except you left in my _foo_ placeholders :) 

Outside of that this is the right level of detail. Essentially I am looking for something detailed enough that it would be appropriate for an SOW in a contract. And this meets that bar. Now we just need to get feedback from the collab space folks!

**Comment by mhdawson** [comment]
Does this list exist `OpenJS projects on the list of critical projects`? I'd be interested in taking a look as well as understanding how it was generated.

**Comment by ljharb** [comment]
@mhdawson → #23

**Comment by bensternthal** [comment]
@mhdawson [OSTIF](https://ostif.org/) has been our partner in developing a prioritized list of projects. They've presented to the security collab space and if you are interested in learning more, I would encourage you to join those meetings. Note when we have some shareable docs, we will make them broadly available.

**Comment by mhdawson** [comment]
@bensternthal thanks, I just wanted to see what was on the list.

**Comment by ljharb** [comment]
I've added items to the dashboard, and the guide is merged, so I'm marking this as done - if there's more to do let's create a new task :-)
