### ISSUE TITLE
Direct Support To Maintainers Of OpenSSF Best Practices Badge Program

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/security-collab-space#22]
```[tasklist]
### Tasks
- [x] #35
- [ ] #36
- [x] #50
- [x] #60 Publish "Best Practices For OpenSSF Badges & JS Projects"
```

# Create Document Summarizing Findings and Recommendations
 - Specifics to be determined via previous step's implementation.

# Create Roadmap For Implementation
 1. approach remaining critical projects, and for each:
    1. assess willingness to land the badge and/or take action to improve project security
    1. offer to do the criteria questionnaire for them and make the badge PR
    1. offer to make PRs for low-hanging fruit (security policy, etc/eg)
 1. create roadmap with plans for doing that work

# Execute Roadmap
 1. Do the thing
 1. write up a postmortem/summary describing the state of things, which actions were taken, which could be in the future, and why (or why not)

**Comment by ljharb** [comment]
Here's what I'm thinking for my rough plan here:
 1. review/complete https://bestpractices.coreinfrastructure.org/ for nvm
    - write down my thoughts, friction, and feedback for OpenSSF as I go through it
    - this will include, which tier(s) qualifies for, and if applicable, which requirements are unattainable for which tiers and why
    - make a PR to add the badge to nvm, and merge it
 1. select another project from the list of critical projects, ideally one published to npm
    - repeat badge process
 1. collate and publish thoughts/FAQ/blog about the process
 1. approach remaining critical projects, and for each:
    - assess willingness to land the badge and/or take action to improve project security
    - offer to do the criteria questionnaire for them and make the badge PR
    - offer to make PRs for low-hanging fruit (security policy, etc/eg)
    - write up a postmortem/summary describing the state of things, which actions were taken, which could be, and why
  1. profit?

I'd love to hear everybody's feedback on this, how it needs to change, and where I could provide more detail!

**Comment by bensternthal** [comment]
@ljharb similar feedback to the other issue. 

1. More details on # 3
2. For # 4 I would suggest thinking about phases. I am not sure how long each of these would take, I would say pick something reasonable for Q3 and let's include that commitment here. If there is too much unknown at this point then I would say we have the development of the phases as the commitment with the number of projects completed in Q3 being TBD

Overall though this seems logical to me and the correct approach.

**Comment by ljharb** [comment]
For item 3, I'm not really sure yet what form this will take - I plan to take notes, in bullet list form, as I move through the process, but until I know what those look like I'm not sure what the best format will be to convey them.

For item 4, I think that the duration is going to depend pretty heavily on the project itself - there's certainly a lot of unknown unknowns here. My hope is that as I complete the questionnaires, I'll get a better sense of what the easy vs challenging projects will be. I think it's very reasonable for Q3 to include nvm and one other npm-published OpenJS project, and *potentially* reasonable to include a couple additional ones - but I'd want that to be a stretch goal until more is known.

**Comment by bensternthal** [comment]
@ljharb can you use the same formatting for this one as you did here #21 ? 

I would suggest the following
* For  # 3 "Create Document Summarizing Findings and Recommendations "
* For #4  I would add a deliverable that is a roadmap, something like "Create Roadmap For Implementation". I think the idea is that there will be a prioritized list that takes into account willingness and complexity.

This is shaping up nicely.

**Comment by bensternthal** [comment]
@ljharb can you integrate your comments into a "definitive" version and add that to the description of this issue following the same formatting as #21 ?

I'd like the description to be the source of truth for the work.

Much thanks!!

**Comment by ljharb** [comment]
@bensternthal I've updated the OP; lmk your thoughts.

**Comment by bensternthal** [comment]
Looks good! I consider this one complete!

**Comment by ljharb** [comment]
Issues filed:
 - https://github.com/coreinfrastructure/best-practices-badge/issues/2000
 - https://github.com/coreinfrastructure/best-practices-badge/issues/1995
 - https://github.com/coreinfrastructure/best-practices-badge/issues/1994
 - https://github.com/coreinfrastructure/best-practices-badge/issues/1993
