### ISSUE TITLE
`security-collab-space` GitHub team is out-of-date

### ISSUE THREAD

**Issue by ctcpip** [openjs-foundation/security-collab-space#221]
we need to update the [GH team for this group](https://github.com/orgs/openjs-foundation/teams/security-collab-space) to remove folks who are no longer participants and add missing participants.  the team membership should match the [list in the readme](https://github.com/openjs-foundation/security-collab-space#collaboration-space-members)

note: we should merge [this PR](https://github.com/openjs-foundation/security-collab-space/pull/213) as part of this as well

**Comment by ctcpip** [comment]
so the team is updated, but it appears the team does not have write access to this repository.  @bensternthal can you resolve?

**Comment by ljharb** [comment]
Done.
