### ISSUE TITLE
Identify Top 10 Tier 1 Projects

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/security-collab-space#23]
Below is a draft list of prioritized projects from OSTIF. Based on the discussion in the security collab space (see first [comment](https://github.com/openjs-foundation/security-collab-space/issues/23#issuecomment-1599298902) in this issue) NVM might be a good first candidate.

1. nvm
2. jQuery
3. Fastify
4. Appium 
5. NativeScript
6. Node.js

**Comment by Amir-Montazery** [comment]
Based on the Security Collab Space Meeting on 6/20/2023 (https://github.com/openjs-foundation/security-collab-space/issues/32), nvm looks like a prime candidate to start the Managed Audit Program.

**Comment by bensternthal** [comment]
@joesepi , thoughts on gaining security collab space consensus on this one?

**Comment by bensternthal** [comment]
I have not seen any comments on this for a week, so I will consider this closed for now. Note this list is not set in stone, we can adjust things as new information becomes available.
