### ISSUE TITLE
Create OpenJS CNA Mailing List

### ISSUE THREAD

**Issue by ruddermann** [openjs-foundation/security-collab-space#237]
On the OpenJS CNA Application we need to provide two separate email addresses with mailing lists. The recommendation for these to are:

- Public Point of Contact: security@openjsf.org
- CNA Mailing List Contact: cna@openjsf.org

**Comment by bensternthal** [comment]
@ruddermann Should these lists be private?

**Comment by bensternthal** [comment]
@ruddermann ping

**Comment by ljharb** [comment]
@bensternthal like, should membership be private? or emails sent to the list?

**Comment by bensternthal** [comment]
@ljharb 

- Public = anyone can view messages on the web
- Private =  limited to those subscribed to the list

We can also control posting permissions, those options are:

- Moderated Discussions: New members cannot post to the list without their emails being approved by a moderator. For new lists, this uses a Groups.io setting that will only moderate users for their first 3 posts.
- Open Discussion: New members can immediately post to the list.
- Announcement: Only moderators can post to the list

**Comment by ljharb** [comment]
I would assume, then, that it must be private, since security reports may come in via that mechanism. For posting permissions, probably open discussion until there's an issue, at which point we'd lock it down to moderated?

**Comment by bensternthal** [comment]
@ruddermann please advise so we can create this.

**Comment by ruddermann** [comment]
Hey @bensternthal  - @ljharb is correct:

- Private
- Open Discussion

**Comment by bensternthal** [comment]
## cna@lists.openjsf.org

- CNA Mailing list created at cna@lists.openjsf.org
- Private list with open discussion
- Added Rudd, Jordan, Ben, Robin to list, happy to add others

## security@openjsf.org

- Is this an email alias? If so where should it forward? @ruddermann

**Comment by UlisesGascon** [comment]
> Added Rudd, Jordan, Ben, Robin to list, happy to add others

I guest that @ctcpip and I can be added based on https://github.com/openjs-foundation/security-collab-space/issues/230#issue-2487141826

**Comment by bensternthal** [comment]
Done.
