### ISSUE TITLE
Create CNA GitHub webpage repo and DNS CNAME

### ISSUE THREAD

**Issue by ruddermann** [openjs-foundation/security-collab-space#238]
The CNA requires a URL for us to post security advisories. Based on the OpenJS CNA Application the consensus is this should be security.openjsf.org.

- The repository for this website will be `security-advisories`
- The GitHub webpage URL will be `openjs-foundation.github.io/security-advisories`
- We will create a DNS CNAME record for security.openjsf.org that redirects to the GitHub webpage URL.

**Comment by ruddermann** [comment]
Howdy @bensternthal! The placeholder website for security advisories is now live: https://openjs-foundation.github.io/security-advisories/

There are two things to do now: 1) configure the security.openjsf.org CNAME record and 2) verify the domain

1) To have security.openjsf.org redirect to the repo page, update the openjsf.org DNS with the following cname record:

`security CNAME openjs-foundation.github.io.` (the extra dot on the end is important)

2) To verify the domain for an organizational site, follow the instructions [here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages#verifying-a-domain-for-your-organization-site). It doesn’t seem that I have the admin privileges to see the Settings link it mentions.

Once these are complete, reassign to @ruddermann and I can finish setting things up!

**Comment by bensternthal** [comment]
This is complete, note I had to configure the custom domain in the security-advisory repo.
