### ISSUE TITLE
Discuss Priority Projects From Initial Audit

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/security-collab-space#31]
Amir & Derek from OSTIF will join the June 20th call to walk us through where we are on identifying priority projects

**Comment by Amir-Montazery** [comment]
Based on the Security Collab Space Meeting on 6/20/2023 (https://github.com/openjs-foundation/security-collab-space/issues/32), **nvm** looks like a prime candidate to start the Managed Audit Program.
