### ISSUE TITLE
Create a prescriptive best practices toolchain

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/security-collab-space#45]
What should be included?
- TBD

Discuss!

Related: #18

**Comment by bensternthal** [comment]
I am certainly not an SME on this subject but folks asked me to give this a shot. At a minimum perhaps this acts as a strawman that gets us to something we all agree on.

## Problem Statement
Creating a secure JS project from scratch is hard and hard to do right.

A granular, templatized, and documented best practices toolchain would help JS developers spin up projects faster and help those project be more secure.

## Example
An example of a toolchain with an example project can be seen on [MDN](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Introducing_complete_toolchain).

**Comment by bensternthal** [comment]
Next Steps!

1. Create categories
2. Decide on potential set of options for each
3. Decide on recommendation for each option
4. Bonus, create an example project that demonstrates usage

**Comment by bensternthal** [comment]
Closed and superseded by https://github.com/openjs-foundation/security-collab-space/issues/78
