### ISSUE TITLE
Having a centralized signing tool for our toolchain

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/security-collab-space#46]

**Comment by mrutkows** [comment]
Signing, SARIF, SBOM, Provenance, Pedigreem (everything) that a Secure Toolchain (CI/CD) would produce. Perhaps using co-sign from Sigstore; for example:

https://docs.digicert.com/en/software-trust-manager/signing-tools/container-signing-with-cosign-and-sigstore.html
