### ISSUE TITLE
Get Feedback On Draft "OpenSSF CII Best Practices Badge for JS Projects"

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/security-collab-space#50]
Review @ljharb  first draft of "OpenSSF CII Best Practices Badge for JS Projects"

Note since it is a draft version Jordan requested we not share publically quite yet. Reach out if you would like access.

**Comment by ljharb** [comment]
I'm ready for wider feedback on https://hackmd.io/y7husZwuT_uh_Jn2WoDpgw?view :-)

**Comment by mhdawson** [comment]
> I'm ready for wider feedback on https://hackmd.io/y7husZwuT_uh_Jn2WoDpgw?view :-)

Can I get access

**Comment by ljharb** [comment]
@mhdawson it should Just Work if you're signed into hackmd (i sign in with github) - if not i can add you explicitly.

**Comment by mhdawson** [comment]
@ljharb thanks, did not clue in that it was not a google doc

**Comment by mhdawson** [comment]
@ljharb took a quick read through, don't have any major comments. It would be good to have @UlisesGascon take a look as he drove a lot of the work the Node.js security team is doing on the badging front.

**Comment by ljharb** [comment]
Absolutely; he's already given it one review and I've asked for a second one :-)

**Comment by bensternthal** [comment]
Doc was published https://github.com/openjs-foundation/security-collab-space/pull/61

Additional tweaks or changes can be handled by filing a new issue.
