### ISSUE TITLE
Discuss: Request for Information on Open-Source Software Security: Areas of Long-Term Focus and Prioritization

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/security-collab-space#53]
https://www.federalregister.gov/documents/2023/08/10/2023-17239/request-for-information-on-open-source-software-security-areas-of-long-term-focus-and-prioritization

Topic: What are the areas where we could make the most impact with government funding?

Note deadline has been extended to November 8th, 2023

**Comment by ljharb** [comment]
One of the largest areas that needs long-term prioritization is in reducing capital burden on OSS maintainers. This could certainly be achieved with funding, but governments could also provide tax credits, healthcare/insurance discounts, etc.

**Comment by mhdawson** [comment]
I think long term funding for the "keep the lights on" work required for critical projects. In that I'd include at least:
- build/infrastructure
- regular releases
- security triage, fixes and security releases

The funding the Node.js project had from the OSSF helped the project keeping up on the security front, and the hope that somehow the project will become 'self sufficient' and that funding will no longer be needed beyond the end of this year does not seem reasonable to me.

**Comment by shusak** [comment]
From a security conscious organization that consume OSS, helping the maintainers get to a more sustainable security stance while important, it is equally important for the actual consumers being able to know who's abiding by it. Real-time badges and scoring information is nice, but even having those packages surface higher in search results, could also be helpful as developers seek out OSS.

**Comment by rginn** [comment]
On Nov 8, 2023, I submitted a response (https://drive.google.com/file/d/1CZBXgzOoqsop3JJmPx24f-KmSECp8tzG/view?usp=sharing) on behalf of the OpenJS Foundation to the US Government’s Office of the National Cyber Director’s Request for Information on Open Source Security: Areas for Long-Term Focus and Prioritization (https://www.whitehouse.gov/oncd/briefing-room/2023/08/10/fact-sheet-office-of-the-national-cyber-director-requests-public-comment-on-open-source-software-security-and-memory-safe-programming-languages/). 

OpenJS proposed two key areas to focus government priorities from the list of potential focus areas that ONCD outlined:

## Focus Area: Behavioral and Economic Incentives to Secure the Open-Source Software ecosystem
### Proposed policy approach. Provide multi-year funding to critical open source projects.
#### Recommendation: Appoint a government agency responsible for providing multi-year funding for open source development and public/private collaboration.

## Focus Area: International Collaboration
### Proposed policy approach. Create a US Government initiative to invest in open source.
#### Recommendation: Learn from, adapt and coordinate with Germany’s Sovereign Tech Fund. Open source development is global yet heavily US-centric. The US government should support the interconnected open source projects that the US economy depends on.

:pray: Thanks to our OpenJS team, the OpenJS Security Collab Space, the Sovereign Tech Fund, Alpha-Omega, and OpenSSF for providing us the experience and expertise that shaped this proposal.
