### ISSUE TITLE
Implement badges on Tier-1 projects

### ISSUE THREAD

**Issue by ljharb** [openjs-foundation/security-collab-space#73]
Have all 7 projects be passing, gaps in silver are explained.

```[tasklist]
### Tasks
 - [ ] Appium
 - [x] Fastify
 - [ ] jQuery
 - [ ] NativeScript
 - [x] Node.js
 - [x] nvm
 - [ ] webpack
```

**Comment by ljharb** [comment]
Current status: All but jQuery have "badge projects", and are close to hitting 100% passing.

This will likely require perseverance with project maintainers, post-holidays, to get this completed.

**Comment by ruddermann** [comment]
Replacing issue for 2024 with https://github.com/openjs-foundation/security-collab-space/issues/154
