### ISSUE TITLE
Pursue PVR and push protection on all Foundation projects

### ISSUE THREAD

**Issue by ljharb** [openjs-foundation/security-collab-space#96]
Request projects to enable PVR and push protection for secrets (as well as branch protections), and whether they do it or not, document the current state in the [dashboard](https://docs.google.com/spreadsheets/d/1wUsWSRu4x_Up4PjVNhEu_z8eOag8V7bcJGaJJl5RlC8/edit#gid=0).
```[tasklist]
### Tasks
- [ ] NativeScript
- [ ] AMP
- [ ] Architect
- [ ] Dojo
- [ ] Esprima
- [ ] Interledger.js
- [ ] Jed
- [ ] JerryScript
- [ ] libuv
- [ ] Marko
- [ ] MessageFormat
- [ ] Mocha
- [ ] Moment
- [ ] RequireJS
- [ ] Sizzle
- [ ] Webhint
- [x] Appium
- [ ] Fastify
- [ ] jQuery
- [ ] Node.js
- [x] nvm
- [ ] webpack
- [ ] Electron
- [ ] ESLint
- [ ] Express
- [ ] Globalize
- [ ] Grunt
- [ ] Intern
- [ ] jQuery UI
- [ ] Lodash
- [ ] LoopBack
- [ ] Node-RED
- [ ] QUnit
- [ ] WebdriverIO
```

**Comment by mhdawson** [comment]
What does PVR stand for. A quick google for PVR and GitHub did not return relevant topics.

**Comment by ljharb** [comment]
Private vulnerability reporting. It’s a native feature on github now.

**Comment by mhdawson** [comment]
@ljharb thanks.

**Comment by ruddermann** [comment]
This issue is being replaced with two new ones:

- https://github.com/openjs-foundation/security-collab-space/issues/129
- https://github.com/openjs-foundation/security-collab-space/issues/133
